# Generated by Django 5.2.6 on 2025-11-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
