# Generated by Django 5.2.6 on 2025-11-11 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_customuser_is_staff_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='@<django.db.models.fields.CharField>', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d81e70dd-4913-4f41-8493-b0fc8d6e2b9e'), primary_key=True, serialize=False),
        ),
    ]
