# Generated by Django 5.2.6 on 2025-11-12 13:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_conversation_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Messages'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_body',
        ),
        migrations.AddField(
            model_name='messages',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('417d6ee7-589c-4757-bb27-27c2b1b20695'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5a99fa8-28d5-438d-8edf-30183f4cea19'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('56fabe73-404e-43ef-bbc1-aeb5b6ca3fc5'), primary_key=True, serialize=False),
        ),
    ]
