# Generated by Django 5.2.6 on 2025-11-21 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chats', '0011_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('GOOGLE', 'google')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c0349649-db4c-44ef-8030-9cde7ba84dc4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e5d4cb5-305e-4366-a098-d8791fe162e6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='Message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a0a1c90f-a0ac-409a-b4be-ce048b3d8bfb'), primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['registration_method'], name='register_idx'),
        ),
    ]
