# Generated by Django 5.2.6 on 2025-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_message_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='message_body_history',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
