# Generated by Django 5.2.6 on 2025-11-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_messagehistory_message_body_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'ordering': ['-edited_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='edited',
        ),
        migrations.RenameField(
            model_name='messagehistory',
            old_name='timestamp',
            new_name='edited_at',
        ),
        migrations.RenameField(
            model_name='messagehistory',
            old_name='performed_by',
            new_name='edited_by',
        ),
    ]
