# Generated by Django 5.2.6 on 2025-11-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_messagehistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
