# Generated by Django 5.2.6 on 2025-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('GUEST', 'guest'), ('ADMIN', 'admin'), ('HOST', 'host')], default='HOST', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='email_idx'), models.Index(fields=['role'], name='role_idx'), models.Index(fields=['id'], name='id_idx'), models.Index(fields=['-created_at'], name='created_desc_idx')],
            },
        ),
    ]
