# Generated by Django 5.2.6 on 2025-11-11 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e74850cc-97e8-493f-b4a5-f28f7c81cb28'), primary_key=True, serialize=False),
        ),
    ]
