# Generated by Django 5.2.6 on 2025-11-11 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_customuser_id_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7a87c97e-fbd0-4ee8-ad19-24591193597b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a0cc5b2-e9f6-4e79-bfc9-ca5466f0a4bd'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(db_index=True, default=uuid.UUID('d868f835-e118-4657-9cc5-7b1b34180501'), primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='chats.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'Message',
            },
        ),
    ]
