# Generated by Django 5.2.6 on 2025-11-12 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5bca7951-2542-491e-8591-d717e56cdd86'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d44e7fd0-7e41-40db-87b4-490b6dc8ef0f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='Message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('fd068be5-b0d3-4ecb-aa1e-117d6b323daa'), primary_key=True, serialize=False),
        ),
    ]
