# Generated by Django 5.2.6 on 2025-11-13 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('fb1b5032-8e08-4197-aa80-6f34956d7e96'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69ef6928-1833-4e96-92eb-7de2e681cad1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e15ea25a-38be-4b72-a774-0b7709afc92c'), primary_key=True, serialize=False),
        ),
    ]
